### ISSUE TITLE
SSL Version Mismatch

### ISSUE THREAD

**Issue by createchange** [PHLAK/docker-mumble#13]
Hello,

I am deploying this Docker container in a Kubernetes cluster. I have an Nginx Ingress set up, which forward the subdomain mumble.domain.com to the Mumble Docker container. I am able to hit the container, but receive the following error when connecting:

```
SSL Version Mismatch: This server is using an older encryption standard, and is no longer supported by modern versions of Mumble.
```

Any ideas on what I need to do in order to resolve this?

**Comment by PHLAK** [comment]
I'm not sure what's going on here. Can you share your Nginx configuration?

The docker image doesn't provide SSL natively, I suspect that might be part of the issue. Your NGINX ingress should be connecting in on the standard port.

**Comment by toby63** [comment]
Could be related to: https://github.com/PHLAK/docker-mumble/issues/16
