### ISSUE TITLE
Does not work on non-x86 cpu architecture (eg. raspberry pi arm32v7)

### ISSUE THREAD

**Issue by ghost** [PHLAK/docker-mumble#27]
[I see this image uses murmur-static that supports only x86](https://github.com/PHLAK/docker-mumble/blob/master/Dockerfile#L27), which I assume makes this image not work on devices with non-x86 cpu architectures like the Raspberry Pi (model 4B in my case)

Error message when launching on raspi: 
```sh
docker logs mumble
standard_init_linux.go:219: exec user process caused: exec format error
```

Would it be possible to use the non-static version? eg from here https://github.com/mumble-voip/mumble/releases/tag/1.3.4 mumble-1.3.4.tar.gz

**Comment by PHLAK** [comment]
We do not provide builds for non-x86 architectures, sorry.

**Comment by ghost** [comment]
If anyone comes across this issue in the future, check out https://github.com/sethidden/umurmur-docker. This isn't exactly the same as this repo, because instead of "murmur" it uses "umurmur" (tiny version meant to run on OpenWRT routers etc.) but it should work more or less the same. Image is currently built for 8 CPU architectures
