### ISSUE TITLE
Mumble 1.4.230 released!

### ISSUE THREAD

**Issue by Marty** [PHLAK/docker-mumble#29]
https://www.mumble.info/blog/mumble-1.4.230/

**Comment by PHLAK** [comment]
Thanks, I'm aware. However, with this release Mumble [stopped distributing a static Linux binary](https://github.com/mumble-voip/mumble/issues/5453) breaking the way I've been building the image up until now. I can still make this work but I'll have to refactor the Dockerfile completely to build Mumble from source instead. I just need to find some time to do this.

**Comment by azlux** [comment]
Mumble will have an official image https://github.com/mumble-voip/mumble-docker
Instead of making the work again, may be you can contribute ?

**Comment by azlux** [comment]
Mumble will have an official image https://github.com/mumble-voip/mumble-docker
Instead of making the work again, may be you can contribute ?

**Comment by PHLAK** [comment]
Good to hear @azlux! I'd be happy to retire this image for an official one. Is there any specific contributions you would like to see?

**Comment by melroy89** [comment]
> Mumble will have an official image https://github.com/mumble-voip/mumble-docker Instead of making the work again, may be you can contribute ?

Docker image repo is gone!

@PHLAK Thanks for your image!

**Comment by melroy89** [comment]
Ah here it is: https://hub.docker.com/r/mumblevoip/mumble-server

**Comment by azlux** [comment]
It's because of a DMCA, we have rewrite the full repo without external code. Publishing right now.

**Comment by melroy89** [comment]
I see. The repo is public again. Good news! 

https://github.com/mumble-voip/mumble-docker

**Comment by PHLAK** [comment]
With an official Mumble image available I will be sun setting this image.

Happy it was useful to so many until now though!
