### ISSUE TITLE
New mumble server version released

### ISSUE THREAD

**Issue by JuniorJPDJ** [PHLAK/docker-mumble#3]
1.3 is here!

**Comment by PHLAK** [comment]
Where do you see this? There's no indication on [their site](https://twitter.com/mumblevoip), [GitHub](https://github.com/mumble-voip/mumble/releases) or [Twitter](https://twitter.com/mumblevoip).

**Comment by JuniorJPDJ** [comment]
Oh, sorry.
My mumble server on debian updated to 1.3.0, but it's git version.
My bad.
